name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
        npm install
        npm run build
      with:
          branch: gh-pages #部署的分支
          folder: dist      

