name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print Message
      run: |
        set -e
        npm run build
        cd docs/.vuepress/dist
        git init
        git add .
        git commit -m 'deploy'
        git push -f git@github.com:paobuji/paobuji.github.io.git master
        cd -


